#!/bin/bash

#PBS -A bany
#PBS -q big_mem
#PBS -l nodes=3:ppn=20
#PBS -l walltime=00:10:00
#PBS -N AlignBlockTest
#PBS -M rvenka21@illinois.edu
#PBS -e /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Test/Task_error.txt
#PBS -o /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Test/Task_output.txt

module load cromwell/cromwell-29
module load wdltool/wdltool-0.14


java -jar $CROMWELL run /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/AlignmentStage_WDL/Tasks/CommandBlockBashScripts/HelloTest.wdl -i /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/AlignmentStage_WDL/Tasks/CommandBlockBashScripts/HelloTest_inputs.json
