#!/bin/bash

#PBS -A bany
#PBS -q big_mem
#PBS -l nodes=3:ppn=20
#PBS -l walltime=00:10:00
#PBS -N AlignBlockTest
#PBS -M rvenka21@illinois.edu
#PBS -m be


module load cromwell/cromwell-29
module load wdltool/wdltool-0.14


cd /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs

java -jar $CROMWELL run /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/MultiSample_WDL_Codes/BWAMem_On_MultipleSamples.wdl -i /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/ConfigFiles/Input_json_Files/BWAMem_On_MultipleSamples_Inputs.json
