#!/bin/bash

#PBS -A aaa
#PBS -q normal
#PBS -l flags=ADVRES:skylake
#PBS -l nodes=1:ppn=20
#PBS -l walltime=00:10:00
#PBS -N AlignBlockTest
#PBS -M rvenka21@illinois.edu
#PBS -e /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/qsubs/error.txt
#PBS -o /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/qsubs/output.txt

truncate --size 0 /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/qsubs/output.txt
truncate --size 0 /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/qsubs/error.txt 
truncate --size 0 /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Exit_Code.txt
truncate --size 0 /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Failure_Logs.txt


module load cromwell/cromwell-29
module load wdltool/wdltool-0.14


cd /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs


echo "The WorkFlow has been initiated for N Samples" | mailx -s "Start of the WorkFlow" rvenka21@illinois.edu

java -jar $CROMWELL run /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/AlignmentStage_WDL/Workflows/TestAlignmentStage.wdl -i /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/ConfigFiles/Input_json_Files/TestAlignmentStage.json -p /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/source.zip

mailx -s "End of the WorkFlow" rvenka21@illinois.edu < /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Failure_Logs.txt



