#!/bin/bash

#PBS -A bany
#PBS -q big_mem
#PBS -l nodes=3:ppn=20
#PBS -l walltime=00:10:00
#PBS -N AlignBlockTest
#PBS -M rvenka21@illinois.edu
#PBS -e /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Task_error.txt
#PBS -o /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Task_output.txt

truncate /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Task_error.txt --size 0
truncate /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Task_output.txt --size 0
truncate /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Exit_Code.txt --size 0
truncate /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs/qsub_info/Failure_Logs.txt --size 0

module load cromwell/cromwell-29
module load wdltool/wdltool-0.14


cd /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/RunOutputs

java -jar $CROMWELL run /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/WOWScripts/MasterWF.wdl -i /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/WOWScripts/MasterWF_inputs.json

