#!/bin/bash
tmpDir=$(mktemp -d /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/execution/tmp.XXXXXX)
chmod 777 $tmpDir
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir

(
cd /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/execution
# Check to see if input files are non-zero
[ -s /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/inputs/projects/bioinformatics/DataPacks/human/EllensSyntheticData/WGS_chr1_5X_E0.005/Chunks/WGS_chr1_5X_E0.005_read1.fq.job03of23.gz ] || echo "Input Read1 FastQ is Empty" >> /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Failure_Logs.txt
[ -s /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/inputs/projects/bioinformatics/DataPacks/human/EllensSyntheticData/WGS_chr1_5X_E0.005/Chunks/WGS_chr1_5X_E0.005_read2.fq.job03of23.gz ] || echo "Input Read2 FastQ is Empty" >> /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Failure_Logs.txt 
#FastQC takes a FastQ file and runs a series of tests on it to generate a comprehensive QC report
/usr/local/apps/bioapps/FastQC/fastqc --extract -j /usr/local/apps/bioapps/java/java-1.8.0_144/jre/bin/java -o /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/FastQCData /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/inputs/projects/bioinformatics/DataPacks/human/EllensSyntheticData/WGS_chr1_5X_E0.005/Chunks/WGS_chr1_5X_E0.005_read1.fq.job03of23.gz /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/inputs/projects/bioinformatics/DataPacks/human/EllensSyntheticData/WGS_chr1_5X_E0.005/Chunks/WGS_chr1_5X_E0.005_read2.fq.job03of23.gz
if [ $? -ne 0 ]; then
   echo "WGS_chr1_5X_E0.005_copy3 has failed at the FASTQ/BAM File Quality Control Step" >> /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Exit_Code.txt
fi
[ ! -d /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/FastQCData ] && echo "FASTQC directory has not been created" >> /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/Failure_Logs.txt
)
echo $? > /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/execution/rc.tmp
(
cd /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/execution

)
sync
mv /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/execution/rc.tmp /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/cromwell-executions/CallFastqQualityControlTask/cfd5eb05-2efb-4f55-8c55-ab43d551bbdb/call-FastqQualityControlTask/shard-2/execution/rc
