#!/bin/bash

#PBS -A bany
#PBS -N Sentieon.bwa.sh
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=40
#PBS -o /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/single_sample_workflow/json_input_files/ramtests/align_test.o
#PBS -e /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/single_sample_workflow/json_input_files/ramtests/align_test.e
#PBS -q super_mem
#PBS -m be

truncate --size 0 /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/single_sample_workflow/json_input_files/ramtests/align_test.e

truncate --size 0 /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/single_sample_workflow/json_input_files/ramtests/align_test.o

cd /projects/mgc/Project_1/ram/CromwellWDL_WorkFlow_Development/WorkflowCodes/Genomics_MGC_GenomeGPS_CromwelWDL/src/single_sample_workflow/

module load  cromwell/cromwell-29

java -jar $CROMWELL run DesignBlock_1/Workflow/TestAlignment.wdl -i json_input_files/InputsAlignmentStage.json
